"""add indexes to recipe table

Revision ID: 263f5c65222b
Revises: 51844cb81ae8
Create Date: 2023-05-08 15:03:34.503259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263f5c65222b'
down_revision = '51844cb81ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_calories_count'), ['calories_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_cooking_time'), ['cooking_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_name'))
        batch_op.drop_index(batch_op.f('ix_recipe_cooking_time'))
        batch_op.drop_index(batch_op.f('ix_recipe_calories_count'))

    # ### end Alembic commands ###
